 language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed rashidramadhan/udagram-api-feed:v4
  - docker tag udagram-api-user rashidramadhan/udagram-api-user:v4
  - docker tag udagram-frontend rashidramadhan/udagram-frontend:v4
  - docker tag reverseproxy rashidramadhan/reverseproxy:v4

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rashidramadhan/udagram-api-feed:v4
  - docker push rashidramadhan/udagram-api-user:v4
  - docker push rashidramadhan/udagram-frontend:v4
  - docker push rashidramadhan/reverseproxy:v4


